export const HOME = '/'
export const LOGIN = '/login'
export const RESERVATIONS = '/reservas'
export const SCHEDULE = '/agendar'
export const MORE = '/mais'
export const CHECKOUT = '/checkout'
export const CHOOSE_PROFESSIONAL = '/escolher-profissional'
export const CHOOSE_PIZZA_QUANTITY = '/escolher-quantidade'
